"""
Alkahest Python bindings for ERC20, ERC721, ERC1155, and token bundle operations.
"""

from .alkahest_py import (
    PyAlkahestClient as AlkahestClient,
    EnvTestManager as EnvTestManager,
    PyMockERC20 as MockERC20,
    PyMockERC721 as MockERC721,
    PyMockERC1155 as MockERC1155,
    PyWalletProvider as WalletProvider,
    PyERC20EscrowObligationData as ERC20EscrowObligationData,
    PyERC20PaymentObligationData as ERC20PaymentObligationData,
    PyERC721EscrowObligationData as ERC721EscrowObligationData,
    PyERC721PaymentObligationData as ERC721PaymentObligationData,
    PyERC1155EscrowObligationData as ERC1155EscrowObligationData,
    PyERC1155PaymentObligationData as ERC1155PaymentObligationData,
    PyNativeTokenEscrowObligationData as NativeTokenEscrowObligationData,
    PyTokenBundleEscrowObligationData as TokenBundleEscrowObligationData,
    PyAttestationEscrowV1ObligationData as AttestationEscrowV1ObligationData,
    PyAttestationEscrowV2ObligationData as AttestationEscrowV2ObligationData,
    StringObligationClient,
    PyStringObligationData as StringObligationData,
    CommitRevealObligationClient,
    PyCommitRevealObligationData as CommitRevealObligationData,
    OracleClient,
    PyOracleAddresses as OracleAddresses,
    PyOracleAttestation as OracleAttestation,
    PyDecision as Decision,
    PyArbitrationMode as ArbitrationMode,
    # Arbiter DemandData types
    PyTrustedOracleArbiterDemandData as TrustedOracleArbiterDemandData,
    IntrinsicsArbiter2DemandData as IntrinsicsArbiter2DemandData,
    ERC8004ArbiterDemandData as ERC8004ArbiterDemandData,
    AttesterArbiterDemandData as AttesterArbiterDemandData,
    RecipientArbiterDemandData as RecipientArbiterDemandData,
    SchemaArbiterDemandData as SchemaArbiterDemandData,
    UidArbiterDemandData as UidArbiterDemandData,
    RefUidArbiterDemandData as RefUidArbiterDemandData,
    RevocableArbiterDemandData as RevocableArbiterDemandData,
    TimeAfterArbiterDemandData as TimeAfterArbiterDemandData,
    TimeBeforeArbiterDemandData as TimeBeforeArbiterDemandData,
    TimeEqualArbiterDemandData as TimeEqualArbiterDemandData,
    ExpirationTimeAfterArbiterDemandData as ExpirationTimeAfterArbiterDemandData,
    ExpirationTimeBeforeArbiterDemandData as ExpirationTimeBeforeArbiterDemandData,
    ExpirationTimeEqualArbiterDemandData as ExpirationTimeEqualArbiterDemandData,
    PyDecodedAllArbiterDemandData as DecodedAllArbiterDemandData,
    PyDecodedAnyArbiterDemandData as DecodedAnyArbiterDemandData,
    PyDecodedDemand as DecodedDemand,
    PyErc20Data as Erc20Data,
    # Address Configuration Classes
    PyErc20Addresses as Erc20Addresses,
    PyErc721Addresses as Erc721Addresses,
    PyErc1155Addresses as Erc1155Addresses,
    PyTokenBundleAddresses as TokenBundleAddresses,
    PyAttestationAddresses as AttestationAddresses,
    PyStringObligationAddresses as StringObligationAddresses,
    PyCommitRevealObligationAddresses as CommitRevealObligationAddresses,
    PyArbitersAddresses as ArbitersAddresses,
    PyDefaultExtensionConfig as DefaultExtensionConfig,
    # IEAS Types
    PyAttestation as Attestation,
    PyAttestationRequest as AttestationRequest,
    PyAttestationRequestData as AttestationRequestData,
    PyAttested as Attested,
    PyRevocationRequest as RevocationRequest,
    PyRevocationRequestData as RevocationRequestData,
    PyRevoked as Revoked,
    PyTimestamped as Timestamped,
)

__all__ = [
    "AlkahestClient",
    "EnvTestManager", 
    "MockERC20",
    "MockERC721",
    "MockERC1155",
    "WalletProvider",
    "ERC20EscrowObligationData",
    "ERC20PaymentObligationData",
    "ERC721EscrowObligationData",
    "ERC721PaymentObligationData",
    "ERC1155EscrowObligationData",
    "ERC1155PaymentObligationData",
    "NativeTokenEscrowObligationData",
    "TokenBundleEscrowObligationData",
    "AttestationEscrowV1ObligationData",
    "AttestationEscrowV2ObligationData",
    "StringObligationClient",
    "StringObligationData",
    "CommitRevealObligationClient",
    "CommitRevealObligationData",
    "DecodedAttestation",
    "OracleClient",
    "OracleAddresses",
    "OracleAttestation",
    "Decision",
    "ArbitrationMode",
    # Arbiter DemandData types
    "TrustedOracleArbiterDemandData",
    "IntrinsicsArbiter2DemandData",
    "ERC8004ArbiterDemandData",
    "AttesterArbiterDemandData",
    "RecipientArbiterDemandData",
    "SchemaArbiterDemandData",
    "UidArbiterDemandData",
    "RefUidArbiterDemandData",
    "RevocableArbiterDemandData",
    "TimeAfterArbiterDemandData",
    "TimeBeforeArbiterDemandData",
    "TimeEqualArbiterDemandData",
    "ExpirationTimeAfterArbiterDemandData",
    "ExpirationTimeBeforeArbiterDemandData",
    "ExpirationTimeEqualArbiterDemandData",
    "DecodedAllArbiterDemandData",
    "DecodedAnyArbiterDemandData",
    "DecodedDemand",
    "Erc20Data",
    # Address Configuration Classes
    "Erc20Addresses",
    "Erc721Addresses", 
    "Erc1155Addresses",
    "TokenBundleAddresses",
    "AttestationAddresses",
    "StringObligationAddresses",
    "CommitRevealObligationAddresses",
    "ArbitersAddresses",
    "DefaultExtensionConfig",
    # IEAS Types
    "Attestation",
    "AttestationRequest",
    "AttestationRequestData",
    "Attested",
    "RevocationRequest",
    "RevocationRequestData",
    "Revoked",
    "Timestamped",
]